config/routes.rb
Draftcomment::Application.routes.draw do
  root 'posts#index'

  resources :posts do
      resources :comments do
        collection do
          put :approve
        end
      end
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	scope :approved, -> { where status: 'approved'}
  scope :draft, -> { where status: 'draft'}
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.all
  end
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.status = "draft"
    if @comment.save
      redirect_to post_path(@post), notice: "Thank you. Your comment was created and is awaiting moderation. Once approved it will appear on this page momentarily."
    else
      render :new
    end
  end

  def approve
    Comment.update_all({status: "approved"}, {id: params[:comment_ids]})
    redirect_to post_comments_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id, :creator, :status)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:success] = "Post created"
			redirect_to root_path
		else
			flash[:error] = "Could not create Post"
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
		#@commentable = @post
		@comments = @post.comments
		@comment = Comment.new
	end

	def edit
		@post = Post.find(params[:id])
	end
	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			flash[:success] = "Post updated"
			redirect_to root_path
		else
			flash[:error] = "Could not update Post"
			render 'edit'
		end
	end

	def delete
		Post.find([:id]).destroy
		flash[:success] = "Post deleted"
		redirect_to root
	end

	private

	def post_params
		params.require(:post).permit(:title, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comments.html.erb
<div class="large-6 large-centered columns">
	<%= link_to "Moderate #{pluralize @comments.draft.size, ('comment')}", post_comments_path(@post), class: "button alert small"%> <br>#you could hide this button with authorization.
</div> 
	<br>
<div class="large-6 large-centered columns panel">
	<h4>Comments</h4>
	<% @comments.approved.each do |comment| %>
    <font color="gray"><%= comment.creator %> about <%= time_ago_in_words(comment.created_at)%></font>
   	<em><%= simple_format(comment.body) %></em>
    <hr>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
	<p align="center"><strong>POST</strong> <em>your</em> <strong>THOUGHTS</strong></p>
  <%= f.text_field :creator, placeholder: 'Your name here' %> 
  <%= f.text_area :body, rows: 90, placeholder: 'Type your thoughts here...' %> 
  
  <small><font color="gray">
  	Comments are moderated to ensure quality conversation. Your comment(s) will appear here when approved. 
  </font></small> <br><br>

  <%= f.submit "Post this comment", class: "button small" %> 

<% end %>

app/views/comments/index.html.erb
<div class="row">
  <div class="large-8 large-centered columns">
    <h5><small>Comments for the post titled:</small> <%= @post.title %></h5>
    <hr>
    <h5>Moderation table</h5>
    <%= form_tag approve_post_comments_path, method: :put do %>
    <table>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Comment</th>
      <th>Status</th>

    </tr>

      <% @post.comments.draft.each do |comment| %>
      <tr>
        <td><%= check_box_tag "comment_ids[]", comment.id %></td>
        <td><%= comment.creator %> </td>
        <td><%= comment.body %></td>
        <td><%= comment.status%></td>
      
      </tr>
      <% end %>
    </table>
      <%= submit_tag "Approve Comments"%> 
    <% end %>

<h5>All Approved Comments</h5>
<table>
  <tr>
    <th>id</th>
    <th>Name</th>
    <th>Comment</th>
    <th>Status</th>

  </tr>
  <% @post.comments.approved.each do |comment| %>
  <tr>
    <td><%= comment.id %></td>
    <td><%= comment.creator %></td>
    <td><%= comment.body %></td>
    <td><%= comment.status%></td>
    
  </tr>
  <% end %>
</table>

<hr>

<p>Note: You could of-course add edit and delete links there.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    <hr>
    <%= link_to 'Home', root_path %>
    <hr>
    <h5>Edit Post</h5>  
    <%= form_for @post do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %> <br>
      <%= f.label :content %>
      <%= f.text_area :content %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
  	<hr>
  	Welcome | <%= link_to 'New Post', new_post_path%>
  	<hr>
    <% @posts.each do |post|%>
      <strong><%= link_to post.title, post_path(post) %> <br><small>This post has <%= pluralize post.comments.size, ('comment') %></small></strong>
      <%= simple_format(post.content) %>

      <hr>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    <hr>
    <%= link_to 'Home', root_path %>
    <hr>
    <h5>New Post</h5>  
    <%= form_for @post do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %> <br>
      <%= f.label :content %>
      <%= f.text_area :content %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
  	<hr>
    <%= link_to 'Home', root_path %>
    <hr>
      <h3><%= @post.title %> <small><%= link_to 'Edit this post', edit_post_path(@post)%></small></h3>
      <%= simple_format(@post.content) %>
      
      <hr>
  </div>
</div>

<div class="row">
  <div class="large-6 large-centered columns">
    <%= render "comments/form" %>
  </div>
   <%= render "comments/comments" %>
</div>